baseURL = 'https://jucaaquino.com/'
languageCode = 'en-us'
title = 'Juca Aquino'
pluralizelisttitles = false
markup.goldmark.renderer.unsafe= true

[params]
    author = "Juca Aquino"
    description = "Juca Aquino artist portfolio website"

[[menu.main]]
    name = 'Work'
    url = '/work/'
    weight = 1
[[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 3
[[menu.main]]
    name = 'Contact'
    url = '/contact/'
    weight = 4
